package errmsg
// Error strings


const ErrRefreshToken = "refresh token is invalid  login again "
const ErrGetDB = "error in retriving data from database"
const ErrWriteDB = "error in writing data to database"
const ErrAccessToken = "error in creating new accesstoken"
const ErrServer = "internal server error"
const ErrOtpValidate ="failed to validate otp"
const ErrDataIsNot = "data is not"
const ErrAlphabet = "data contains non-alphabetic characters"
const ErrUserExist = "user does not exist"
const ErrDb = "data base error"
const ErrProductExist  = "product does not exist"
const ErrCartFalse = "no cart found"


const StatusApprove = "approved"

// Message strings
const DbErr = "Data base error"

const MsgConstraintsErr = "Constraints not satisfied"
const MsgAuthUserErr = "Cannot authenticate user"
const MsgFormatErr = "Details is not in correct format"
const MsgLoginSucces = "Logined successfully"
const MsgUserBlockErr = "User could not be blocked"
const MsgUserBlockSucces = "Successfully blocked the user"
const MsgUserUnBlockErr = "User could not be unblocked"
const MsgUserUnBlockSucces = "Successfully unblocked the user"
const MsgPageNumFormatErr = "page number not in right format"
const MsgPageCountErr = "page count not in right format"
const MsgGettingDataErr = "could not retrieve Data"
const MsgGetSucces = "Successfully retrieved the Data"
const MsgEmptyDateErr = "Start or End date is empty"
const MsgGetErr = "error in getting"
const MsgPrintErr = "error in printing"
const MsgServErr = "Error in serving the sales report"
const MsgSuccess = "Success"
const MsgBadRequestErr = "bad request"
const MsgAddSuccess = "Successfully Added"
const MsgAddCartErr = "Cannot Add to Cart"
const MsgListErr = "Cannot list data"
const MsgListingErr = "Product cannot be displayed"
const MsgUpdateQuantityErr = "Cannot update quantity"
const MsgQuantityUpdationFailErr = "Updating quantity Failed"
const MsgRemoveCartErr = "Removing from cart is Failed"
const MsgAddErr = "Could not add"
const MsgUpdateErr = "Could not update"
const MsgCouponExpiryErr = "Coupon cannot be made invalid"
const MsgOTPSentErr = "OTP not sent"
const MsgOTPVerifyErr = "Could not verify OTP"
const MsgOTPSentSuccess = "OTP sent successfully"
const MsgOTPVerifySuccess = "Successfully verified OTP"
const MsgPaymentErr = "Cannot make payment"
const MsgErr = "error"
const MsgUpdateSuccess = "Successfully Updated"
const MsgUserIdErr = "user_id not found"
const MsgRequiredUserIdErr = "user_id is required"
const MsgInvalidIdErr = "invalid user_id type"
const MsgIdDatatypeErr = "user_id must be an integer"
const MsgEditErr = "could not edit the data"
const MsgStockUpdateErr = "Could  not update the product stock"
const MsgConvErr = "conversion error"
const MsdGetIdErr = "Failed to get user id"
const MsgLoginErr = "user could not be logged in"
const MsgSignUperr = "user could not signed up"
const MsgIdErr = "error in reading the order id"
const MsgCanelErr = "Couldn't cancel the order"
const MsgOrderApproveErr = "Couldn't approve the order"
const MsgOrderErr = "Could not do the order"
const MsgCheckoutErr = "CheckOut Failed"
const MsgTokenErr = "Invalid Authorization Token error"
const MsgTokenMissingErr = "Missing authorization token"
const MsgUnAuthErr = "Unauthorized access"
const MsgIdGetErr = "Error retrieving ID"
